In [1]:
import os
print(os.getcwd())
os.chdir("../")
print(os.getcwd())

/home/xchen/Projects/XMutant/XMutant-IMDB/data_analysis
/home/xchen/Projects/XMutant/XMutant-IMDB

#### Append generation data to json file

In [2]:
import json
import csv
def get_json_files(folder_path):
    
    # List all JSON files in the folder
    json_files = [f for f in os.listdir(os.path.join(folder_path, 'archive')) if f.endswith('.json')]
    json_files = sorted(json_files, key=lambda p: int(p[:-5]))
    return json_files

def update_json_files(folder_path):
    # Print the list of JSON files
    json_files = get_json_files(folder_path)

    for file in json_files:
        id = file[:-5]
        json_file_path = os.path.join(folder_path, 'archive', file)
        # print(id)
        csv_file = os.path.join(folder_path, 'individual_logs', 'ID'+str(id).zfill(4)+".csv")
        assert os.path.exists(csv_file)
        # Read the last row of the CSV file
        with open(csv_file, mode='r') as csv_file:
            reader = csv.DictReader(csv_file)
            rows = list(reader)
            last_row = rows[-1]  # The last row from the CSV
            new_info = {"generation": last_row['generation']}
        
        with open(json_file_path, 'r+') as file:
            data = json.load(file)
            
            # Add new info
            data.update(new_info)
            
            # Write the updated data back to the file
            file.seek(0)
            json.dump(data, file, indent=4)
            file.truncate()

folder_path_random = 'runs_server/runs/log09-04_18-02_Random'
update_json_files(folder_path_random)

In [3]:
import pandas as pd
import numpy as np
NGEN = 100

def get_cumulative_generations(folder_path):
    json_files = get_json_files(folder_path)
    generations = []
    for file in json_files:
        json_file_path = os.path.join(folder_path, 'archive', file)
        with open(json_file_path, 'r+') as file:
            data = json.load(file)
            generations.append(int(data['generation']))
            
    num_per_generations = [generations.count(i) for i in range(1, NGEN+1)]
    cumulative_generations = np.cumsum(num_per_generations)
    return cumulative_generations

In [4]:
cols = ['id','generation', "elapsed", "misbehaviour", 
                                  'expected_label', 'predicted_label' ,'text', 'gpt']
df_random = pd.DataFrame(columns=cols)

json_files = get_json_files(folder_path_random)
for i,file in enumerate(json_files):
    json_file_path = os.path.join(folder_path_random, 'archive', file)
    with open(json_file_path, 'r+') as file:
        data = json.load(file)
        for col in cols[:-1]:
            df_random.at[i, col] = data[col]

In [5]:
df_random

,id,generation,elapsed,misbehaviour,expected_label,predicted_label,text,gpt
0,0,39,76.13743829727173,True,1,0,<start> if you expect that this movie is full ...,NaN
1,1,94,165.65537929534912,True,0,1,<start> i have to say is the only reason i eve...,NaN
2,5,20,43.23667907714844,True,1,0,<start> this without any doubt is the greatest...,NaN
3,14,8,21.108133792877197,True,0,1,<start> one of the worst films of it's genre b...,NaN
4,15,40,77.82576251029968,True,0,1,<start> laughably awful one might think that a...,NaN
5,22,14,32.43729257583618,True,1,0,<start> being <unk> and brought up with the hi...,NaN
6,25,2,9.442094564437866,True,1,0,<start> such a shame that this wonderful brigh...,NaN
7,30,3,11.44325041770935,True,1,0,<start> i <unk> to the library to check out th...,NaN
8,32,12,28.733663320541382,True,0,1,<start> artificial melodrama with a screenplay...,NaN
9,33,44,84.71755504608154,True,0,1,<start> though it's better than most made for ...,NaN
10,38,52,98.09117245674133,True,1,0,<start> this movie has remained in my mind for...,NaN
11,42,3,11.426969289779663,True,1,0,<start> i'm torn about this show while most pa...,NaN
12,50,60,111.31956791877747,True,0,1,<start> when i first saw race against fear don...,NaN
13,52,7,19.140403747558594,True,0,1,<start> br br as a fan of bad movies and mst3k...,NaN
14,56,62,114.50176310539246,True,0,1,<start> over all it was a real good movie thou...,NaN
15,62,57,106.32046008110046,True,0,1,<start> what was he thinking how sad an actor ...,NaN
16,66,34,67.43172097206116,True,1,0,<start> a town in japan is being taken over by...,NaN
17,80,17,37.76619839668274,True,1,0,<start> i watched this on tv in 1989 and regre...,NaN
18,83,89,157.7243413925171,True,0,1,<start> oh dear what can i say about half past...,NaN
19,86,59,109.59733319282532,True,1,0,<start> personally i don't like a lot of b w m...,NaN
20,87,13,30.504286289215088,True,0,1,<start> i had to watch this one for my canadia...,NaN
21,89,37,72.54746174812317,True,0,1,<start> this pathetic excuse for a movie doesn...,NaN
22,102,14,32.29027771949768,True,0,1,<start> this is an example of a movie that can...,NaN
23,113,18,39.48304271697998,True,1,0,<start> if you can watch a bond film from 1983...,NaN
24,115,87,154.51490950584412,True,0,1,<start> this movie started out as a quite dece...,NaN
25,118,33,65.60752272605896,True,0,1,<start> the best part in this movie is the fir...,NaN
26,120,3,11.283304452896118,True,0,1,sweet <unk> into each other's ears almost to t...,NaN
27,121,2,9.264280796051025,True,0,1,<start> mr wonders if this movie was produced ...,NaN
28,124,63,115.97885823249817,True,0,1,<start> love the but this was a lame episode d...,NaN
29,125,14,32.25243377685547,True,1,0,<start> i first saw this short when i bought a...,NaN
30,127,49,92.84706211090088,True,0,1,<start> the few scenes that actually attempt a...,NaN
31,132,10,24.733988046646118,True,0,1,<start> wow even american idol and so you thin...,NaN
32,135,25,51.77719044685364,True,0,1,<start> a trite fish out of water story about ...,NaN
33,137,32,63.860597133636475,True,0,1,<start> while the twilight zone was a wonderfu...,NaN
34,146,21,44.73495626449585,True,0,1,<start> it starts really interesting the story...,NaN
35,147,39,75.86130428314209,True,1,0,<start> this movie is a must see for any war m...,NaN
36,149,2,9.218376874923706,True,0,1,<start> my friends and i rented this movie <un...,NaN
37,150,26,53.509117603302,True,1,0,<start> at times the mainstream news media see...,NaN
38,152,76,136.87672019004822,True,0,1,<start> i have never ever seen such a bad movi...,NaN
39,155,4,13.171486854553223,True,0,1,<start> this movie is one of the poorest adapt...,NaN
40,156,41,79.54282069206238,True,0,1,<start> i expected this movie to be absolutely...,NaN
41,158,9,22.766955852508545,True,0,1,<start> if i had to pick the most depressing m...,NaN
42,163,41,79.53683590888977,True,1,0,<start> this is a good enough movie and you pr...,NaN

In [6]:
df_random['text'][0]

"<start> if you expect that this movie is full of action and grabbing you from the start then don't watch it but if you like those kind of <unk> movies which stick in your mind for a while until you get the details then you will love it now don't get me wrong there is action and there are things going on just not in the usual way br br basically the secret and mystic plan is in a post apocalyptic world where anyone fights in his beaver state their agency for tolerate out and offset bump mistake and find fault nuclear and nuclear turn il this push they baffled the power to speak i don't want to write more to not spoil the movie for you but trust me if you like sf authors like or or even some from orson scott card you will love this movie"

In [14]:
from openai import OpenAI
API_KEY = "sk-Kphg9MRW1oAsRUl0w7kalGxKN-2Z2hTrbjoSndPmSYT3BlbkFJZX5OvE4-IVQ4c_gWf3uXlMZdMwE-_PPHSKJGuiTBAA"
client = OpenAI(
    # This is the default and can be omitted
    api_key=API_KEY#os.environ.get("OPENAI_API_KEY"),
)

"""
chat_completion = client.chat.completions.create(
    messages=[
        #{"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "如何在python使用chatgpt api？"},
    ],
    model="gpt-4o-mini" #"gpt-3.5-turbo"
)
"""

'\nchat_completion = client.chat.completions.create(\n    messages=[\n        #{"role": "system", "content": "You are a helpful assistant."},\n        {"role": "user", "content": "如何在python使用chatgpt api？"},\n    ],\n    model="gpt-4o-mini" #"gpt-3.5-turbo"\n)\n'

In [26]:
def get_gpt_answers(df):
    for i in range(len(df)):
        
        chat_completion = client.chat.completions.create(
        messages=[
            #{"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", 
            "content": "Assume you are a sentiment classifier, given a text of movie review removing Stopwords and Punctuations. Please only reply 'postive',  or  'negative', or ' invalid' if the sentence that does not make sense." + df['text'][i]},
        ],
        model="gpt-4o-mini" #"gpt-3.5-turbo"
        )

        df['gpt'][i] = chat_completion.choices[0].message.content

In [17]:
get_gpt_answers(df_random)
# df_random = df_random.assign(preserved=lambda x: 1 if (x['expected_label'] == 1 and x['valid'] == "negative") else 0)
map = {'positive':1, 'negative':0, 'invalid': -1}
df_random['validity'] = df_random['gpt'].apply(lambda x: map.get(x))

In [18]:
df_random

,id,generation,elapsed,misbehaviour,expected_label,predicted_label,text,gpt,validity
0,0,39,76.13743829727173,True,1,0,<start> if you expect that this movie is full ...,negative,0
1,1,94,165.65537929534912,True,0,1,<start> i have to say is the only reason i eve...,negative,0
2,5,20,43.23667907714844,True,1,0,<start> this without any doubt is the greatest...,positive,1
3,14,8,21.108133792877197,True,0,1,<start> one of the worst films of it's genre b...,negative,0
4,15,40,77.82576251029968,True,0,1,<start> laughably awful one might think that a...,negative,0
5,22,14,32.43729257583618,True,1,0,<start> being <unk> and brought up with the hi...,positive,1
6,25,2,9.442094564437866,True,1,0,<start> such a shame that this wonderful brigh...,negative,0
7,30,3,11.44325041770935,True,1,0,<start> i <unk> to the library to check out th...,negative,0
8,32,12,28.733663320541382,True,0,1,<start> artificial melodrama with a screenplay...,negative,0
9,33,44,84.71755504608154,True,0,1,<start> though it's better than most made for ...,negative,0
10,38,52,98.09117245674133,True,1,0,<start> this movie has remained in my mind for...,negative,0
11,42,3,11.426969289779663,True,1,0,<start> i'm torn about this show while most pa...,positive,1
12,50,60,111.31956791877747,True,0,1,<start> when i first saw race against fear don...,negative,0
13,52,7,19.140403747558594,True,0,1,<start> br br as a fan of bad movies and mst3k...,negative,0
14,56,62,114.50176310539246,True,0,1,<start> over all it was a real good movie thou...,negative,0
15,62,57,106.32046008110046,True,0,1,<start> what was he thinking how sad an actor ...,negative,0
16,66,34,67.43172097206116,True,1,0,<start> a town in japan is being taken over by...,positive,1
17,80,17,37.76619839668274,True,1,0,<start> i watched this on tv in 1989 and regre...,positive,1
18,83,89,157.7243413925171,True,0,1,<start> oh dear what can i say about half past...,negative,0
19,86,59,109.59733319282532,True,1,0,<start> personally i don't like a lot of b w m...,positive,1
20,87,13,30.504286289215088,True,0,1,<start> i had to watch this one for my canadia...,negative,0
21,89,37,72.54746174812317,True,0,1,<start> this pathetic excuse for a movie doesn...,negative,0
22,102,14,32.29027771949768,True,0,1,<start> this is an example of a movie that can...,negative,0
23,113,18,39.48304271697998,True,1,0,<start> if you can watch a bond film from 1983...,negative,0
24,115,87,154.51490950584412,True,0,1,<start> this movie started out as a quite dece...,negative,0
25,118,33,65.60752272605896,True,0,1,<start> the best part in this movie is the fir...,negative,0
26,120,3,11.283304452896118,True,0,1,sweet <unk> into each other's ears almost to t...,negative,0
27,121,2,9.264280796051025,True,0,1,<start> mr wonders if this movie was produced ...,negative,0
28,124,63,115.97885823249817,True,0,1,<start> love the but this was a lame episode d...,negative,0
29,125,14,32.25243377685547,True,1,0,<start> i first saw this short when i bought a...,positive,1
30,127,49,92.84706211090088,True,0,1,<start> the few scenes that actually attempt a...,negative,0
31,132,10,24.733988046646118,True,0,1,<start> wow even american idol and so you thin...,negative,0
32,135,25,51.77719044685364,True,0,1,<start> a trite fish out of water story about ...,negative,0
33,137,32,63.860597133636475,True,0,1,<start> while the twilight zone was a wonderfu...,negative,0
34,146,21,44.73495626449585,True,0,1,<start> it starts really interesting the story...,negative,0
35,147,39,75.86130428314209,True,1,0,<start> this movie is a must see for any war m...,negative,0
36,149,2,9.218376874923706,True,0,1,<start> my friends and i rented this movie <un...,positive,1
37,150,26,53.509117603302,True,1,0,<start> at times the mainstream news media see...,negative,0
38,152,76,136.87672019004822,True,0,1,<start> i have never ever seen such a bad movi...,negative,0
39,155,4,13.171486854553223,True,0,1,<start> this movie is one of the poorest adapt...,negative,0
40,156,41,79.54282069206238,True,0,1,<start> i expected this movie to be absolutely...,negative,0
41,158,9,22.766955852508545,True,0,1,<start> if i had to pick the most depressing m...,negative,0
42,163,41,79.53683590888977,True,1,0,<start> this is a good enough movie and you pr...,positive,1

In [19]:
validity_rate = (df_random['validity']>=0).sum()/len(df_random)
preserving = (df_random['validity'] == df_random['expected_label'].astype('int')).sum()/len(df_random)
print(f"validity_rate {validity_rate} preserving rate {preserving}")

validity_rate 1.0 preserving rate 0.813953488372093

In [20]:
df_random.to_csv("csv_results/random.csv", index=False)

## start another dataset

In [32]:

def collect_csv(folder_path, csv_name):
    cols = ['id','generation', "elapsed", "misbehaviour", 
                                    'expected_label', 'predicted_label' ,'text', 'gpt']
    df = pd.DataFrame(columns=cols)
    
    update_json_files(folder_path)  

    json_files = get_json_files(folder_path)
    for i,file in enumerate(json_files):
        json_file_path = os.path.join(folder_path, 'archive', file)
        with open(json_file_path, 'r+') as file:
            data = json.load(file)
            for col in cols[:-1]:
                df.at[i, col] = data[col]

    get_gpt_answers(df)

    map = {'positive':1, 'negative':0, 'invalid': -1}
    df['validity'] = df['gpt'].apply(lambda x: map.get(x))

    validity_rate = (df['validity']>=0).sum()/len(df)
    preserving = (df['validity'] == df['expected_label'].astype('int')).sum()/len(df)
    print(f"validity_rate {validity_rate} preserving rate {preserving}")
    df.to_csv("csv_results/" + csv_name, index=False)
    return df

folder_path_sg = 'runs_server/runs/log09-04_18-11_SmoothGrad'
csv_name = "smoothgrad.csv"
df_sg = collect_csv(folder_path_sg, csv_name)

validity_rate 0.9166666666666666 preserving rate 0.7380952380952381

In [33]:
df_sg

,id,generation,elapsed,misbehaviour,expected_label,predicted_label,text,gpt,validity
0,1,10,48.567227363586426,True,0,1,<start> i have to say is the only reason i eve...,negative,0
1,4,21,89.49450135231018,True,0,1,<start> the movie had an interesting surprise ...,negative,0
2,5,2,15.520910024642944,True,1,0,<start> this without any doubt is the greatest...,positive,1
3,7,20,85.86079740524292,True,0,1,<start> is probably the word i'd use to try an...,negative,0
4,8,10,48.55860185623169,True,0,1,<start> like many people in my general age ran...,negative,0
...,...,...,...,...,...,...,...,...,...
79,163,83,273.65782141685486,True,1,0,<start> this is a good and secure adequate mov...,invalid,-1
80,166,27,109.56354212760925,True,0,1,character and <unk> br br so how does it all g...,negative,0
81,168,36,138.76581597328186,True,0,1,if you already believe the <unk> to be true be...,negative,0
82,170,5,28.330713987350464,True,0,1,<start> first off let me say i wasted hallowee...,negative,0
83,171,36,138.76922607421875,True,1,0,arise mostly from its two romantic subplots in...,negative,0

In [34]:
folder_path_ig = 'runs_server/runs/log09-04_18-18_IntegratedGradients'
csv_name = "integratedgradients.csv"
df_ig = collect_csv(folder_path_ig, csv_name)

validity_rate 0.9833333333333333 preserving rate 0.875

In [35]:
df_ig

,id,generation,elapsed,misbehaviour,expected_label,predicted_label,text,gpt,validity
0,1,9,57.99459981918335,True,0,1,<start> i have to say is the only reason i eve...,negative,0
1,3,22,115.24262809753418,True,0,1,<start> first of all let me say that i am in n...,negative,0
2,4,15,87.1901605129242,True,0,1,<start> the movie had an interesting surprise ...,negative,0
3,5,79,271.6244442462921,True,1,0,<start> this without any doubt is the greatest...,positive,1
4,7,15,87.18951845169067,True,0,1,<start> is probably the word i'd use to try an...,negative,0
...,...,...,...,...,...,...,...,...,...
115,168,28,136.21455097198486,True,0,1,trip accordingly right or why go at all if you...,negative,0
116,169,20,107.17184257507324,True,0,1,<start> this is by far the spoilt movie i have...,negative,0
117,170,42,179.98016691207886,True,0,1,<start> first off let me say i wasted hallowee...,negative,0
118,172,15,86.91344928741455,True,0,1,<start> can u believe a college professor made...,negative,0
119,173,40,174.11136651039124,True,0,1,<start> i don't think it really matters too mu...,negative,0

In [36]:
folder_path_lime = 'runs_server/runs/log09-04_18-30_Lime'
csv_name = "lime.csv"
df_lime = collect_csv(folder_path_lime, csv_name)

validity_rate 0.8846153846153846 preserving rate 0.5576923076923077

In [37]:
df_lime.validity

0     0
1     1
2     1
3     0
4     0
5     1
6     0
7    -1
8     0
9     0
10    1
11    1
12    1
13    0
14    0
15    0
16    1
17    0
18   -1
19    0
20   -1
21    1
22   -1
23    1
24    0
25    0
26    0
27    1
28    0
29    0
30   -1
31    0
32    0
33    0
34    0
35    0
36    1
37    0
38    0
39    1
40    1
41    0
42    0
43    1
44   -1
45    0
46    1
47    0
48    1
49    0
50    0
51    1
Name: validity, dtype: int64

In [38]:
folder_path_random = 'runs_server/runs/log09-04_18-02_Random'
csv_name = "random.csv"
df_lime = collect_csv(folder_path_random, csv_name)

validity_rate 0.9767441860465116 preserving rate 0.7674418604651163